[package]
name = "part1"
version = "0.1.0"
authors = ["Fraser Darwent <fraser@darwen.tf>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
